"""Stable warning codes emitted by pricing outputs."""

FX_INVERTED_QUOTE = "FX_INVERTED_QUOTE"
FUTURE_MTM_ONLY = "FUTURE_MTM_ONLY"
MD_IMPUTED_FFILL = "MD_IMPUTED_FFILL"
MD_STALE_SOURCE_DATE = "MD_STALE_SOURCE_DATE"

ALL_WARNING_CODES = (
    FX_INVERTED_QUOTE,
    FUTURE_MTM_ONLY,
    MD_IMPUTED_FFILL,
    MD_STALE_SOURCE_DATE,
)

__all__ = [
    "FX_INVERTED_QUOTE",
    "FUTURE_MTM_ONLY",
    "MD_IMPUTED_FFILL",
    "MD_STALE_SOURCE_DATE",
    "ALL_WARNING_CODES",
]
